version: '3'

services:

  api:
    image: todo_api
    restart: always
    depends_on:
      - db
      - adminer



  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: Password123#@!
    volumes:
      - mysql-data:/var/lib/mysql




  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql-data: